### ISSUE TITLE
Initialization of mod_jerk_profile

### ISSUE THREAD

**Issue by JakobThumm** [yannickBurkhardt/LongTermPlanner#4]
Hi,
I have the feeling, that `mod_jerk_profile` is wrongly initialized.
https://github.com/yannickBurkhardt/LongTermPlanner/blob/16d44fd72c207460a7d985af60f23f659ef55722/LTPlanner.m#L45
Shouldn't this be
```
mod_jerk_profile = false(1,obj.DoF); 
```

**Comment by yannickBurkhardt** [comment]
You are right, I will fix it.
