### ISSUE TITLE
Usage of real() function

### ISSUE THREAD

**Issue by JakobThumm** [yannickBurkhardt/LongTermPlanner#6]
Why do we need to take the real value here
https://github.com/yannickBurkhardt/LongTermPlanner/blob/b9f268a39a2461e4eb74d087983210343db52d11/LTPlanner.m#L250
I thought `t_rel` is only real since we make sure that `root` is real.

Also, using the name `root` twice
https://github.com/yannickBurkhardt/LongTermPlanner/blob/b9f268a39a2461e4eb74d087983210343db52d11/LTPlanner.m#L230
and 
https://github.com/yannickBurkhardt/LongTermPlanner/blob/b9f268a39a2461e4eb74d087983210343db52d11/LTPlanner.m#L244
is quite confusing. Is this necessary?

**Comment by yannickBurkhardt** [comment]
Yes, line 250 can be deleted.

I use `root` as a temporary variable everytime I calculate the root of an equation and and need to perform checks to find the correct solution/ check if the obtained solution is valid. Giving this temporary variable a different name every time would be more confusing in my opinion.

**Comment by JakobThumm** [comment]
understood :)
